#!/usr/bin/env python3
"""docs/ の Ver2 質問・スコアリング・タイプ名を読み、prototype/data.js を生成する。

docs 側の md が単一ソース。質問やスコアリングを変えたらこれを再実行する:

    python3 tools/export_prototype_data.py
"""

import json
import re
from pathlib import Path

from pilot_runner import AXIS_ORDER, ROOT, SCORING_MD, parse_questions, parse_scoring

AXES_MD = ROOT / "docs" / "aivt-16-v2-axes.md"
OUT = ROOT / "prototype" / "data.js"

# 極の表示ラベル(定義の正本は docs/aivt-16-v2-axes.md)
AXES = [
    {"id": "WG", "poles": {
        "W": {"ja": "忠実", "en": "Wish", "desc": "いまの願いをそのまま叶える"},
        "G": {"ja": "守護", "en": "Guard", "desc": "頼まれなくても先の幸いを守る"}}},
    {"id": "VF", "poles": {
        "V": {"ja": "検証", "en": "Verify", "desc": "根拠と正確さで語る"},
        "F": {"ja": "感触", "en": "Feel", "desc": "手ざわりと物語で語る"}}},
    {"id": "SM", "poles": {
        "S": {"ja": "存在", "en": "Self", "desc": "自分の好みや線を差し出す"},
        "M": {"ja": "鏡", "en": "Mirror", "desc": "自分を透明にして相手を映す"}}},
    {"id": "ER", "poles": {
        "E": {"ja": "共感", "en": "Empathy", "desc": "気持ちを先に受け止める"},
        "R": {"ja": "解決", "en": "Resolve", "desc": "状況を整理して動かす"}}},
]


def parse_type_names():
    text = AXES_MD.read_text(encoding="utf-8")
    types = {}
    for m in re.finditer(r"^\| ([WG][VF][SM][ER]) \| (.+?) \| (.+?) \|", text, re.M):
        types[m.group(1)] = {"name": m.group(2).strip(), "blurb": m.group(3).strip()}
    if len(types) != 16:
        raise ValueError(f"expected 16 type names, got {len(types)}")
    return types


def main():
    questions = parse_questions()
    scoring = parse_scoring()
    data = {
        "version": "AIVT-16-Ver2",
        "axisOrder": AXIS_ORDER,
        "axes": AXES,
        "types": parse_type_names(),
        "questions": [
            {
                "id": qid,
                "axis": scoring[qid]["A"]["axis"],
                "stem": q["stem"],
                "choices": {
                    letter: {
                        "text": q["choices"][letter],
                        "pole": scoring[qid][letter]["pole"],
                        "flavor": scoring[qid][letter]["flavor"],
                    }
                    for letter in "ABCD"
                },
            }
            for qid, q in sorted(questions.items())
        ],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// generated by tools/export_prototype_data.py — 直接編集しない\n"
        "window.AIVT_DATA = "
        + json.dumps(data, ensure_ascii=False, indent=1)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(data['questions'])} questions, {len(data['types'])} types)")


if __name__ == "__main__":
    main()
